# Generated by Django 5.1.2 on 2025-05-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LSCliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuariocliente',
            options={'verbose_name': 'Usuário Cliente', 'verbose_name_plural': 'Usuários Cliente'},
        ),
        migrations.AddField(
            model_name='usuariocliente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/'),
        ),
        migrations.AlterField(
            model_name='usuariocliente',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
