# Generated by Django 5.1.2 on 2025-05-09 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LSCliente', '0002_alter_usuariocliente_options_usuariocliente_foto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariocliente',
            name='foto',
        ),
    ]
