# Generated by Django 5.1.2 on 2025-05-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LSCliente', '0003_remove_usuariocliente_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocliente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/'),
        ),
    ]
