# Generated by Django 5.1.2 on 2025-05-29 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LSCliente', '0002_alter_usuariocliente_options_and_more'),
        ('LSCliente', '0004_usuariocliente_foto'),
    ]

    operations = [
    ]
