# Generated by Django 5.1.2 on 2025-05-29 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LSCliente', '0006_clientesystemsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoUsuarioCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_sessao', models.CharField(max_length=40)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('ultima_atividade', models.DateTimeField(auto_now=True)),
                ('endereco_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='LSCliente.usuariocliente')),
            ],
            options={
                'verbose_name': 'Sessão de Usuário Cliente',
                'verbose_name_plural': 'Sessões de Usuários Cliente',
                'unique_together': {('usuario', 'chave_sessao')},
            },
        ),
    ]
