# Generated by Django 5.1.2 on 2025-06-03 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LSCliente', '0007_sessaousuariocliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Prova')),
                ('materia', models.CharField(max_length=100, verbose_name='Matéria')),
                ('tipo_prova', models.CharField(choices=[('avaliacao', 'Avaliação'), ('simulado', 'Simulado'), ('teste', 'Teste'), ('trabalho', 'Trabalho'), ('prova_bimestral', 'Prova Bimestral'), ('prova_final', 'Prova Final')], max_length=20, verbose_name='Tipo de Prova')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('fonte_padrao', models.CharField(default='Arial', max_length=50, verbose_name='Fonte Padrão')),
                ('tamanho_fonte', models.IntegerField(default=12, verbose_name='Tamanho da Fonte')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provas_criadas', to='LSCliente.usuariocliente')),
            ],
            options={
                'verbose_name': 'Prova',
                'verbose_name_plural': 'Provas',
            },
        ),
        migrations.CreateModel(
            name='QuestaoProva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questao_id', models.IntegerField(verbose_name='ID da Questão do Dashboard')),
                ('questao_dados', models.JSONField(verbose_name='Dados da Questão')),
                ('ordem', models.IntegerField(verbose_name='Ordem na Prova')),
                ('texto_destacado', models.JSONField(blank=True, default=list)),
                ('fonte_customizada', models.CharField(blank=True, max_length=50, null=True)),
                ('prova', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes_prova', to='LSCliente.prova')),
            ],
            options={
                'ordering': ['ordem'],
                'unique_together': {('prova', 'ordem')},
            },
        ),
    ]
