# Generated by Django 5.1.2 on 2025-06-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LSCliente', '0008_prova_questaoprova'),
    ]

    operations = [
        migrations.AddField(
            model_name='prova',
            name='acessibilidade_prova',
            field=models.IntegerField(choices=[(1, 'Grupo 1'), (2, 'Grupo 2'), (3, 'Grupo 3')], default=1, verbose_name='Nível de Acessibilidade da Prova'),
        ),
        migrations.AddField(
            model_name='questaoprova',
            name='acessibilidade_questao',
            field=models.IntegerField(choices=[(1, 'Grupo 1'), (2, 'Grupo 2'), (3, 'Grupo 3')], default=1, verbose_name='Nível de Acessibilidade da Questão'),
        ),
    ]
