# Generated by Django 5.1.2 on 2025-04-15 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LSDash', '0002_alter_usermodel_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='paginas',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='LSDash.pagina'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
