# Generated by Django 5.1.2 on 2025-04-22 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LSDash', '0004_cliente_alter_usermodel_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoEnsino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AnoEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ordem', models.IntegerField(default=0)),
                ('grupo_ensino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anos', to='LSDash.grupoensino')),
            ],
            options={
                'ordering': ['grupo_ensino', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('aberta', 'Questão Aberta'), ('multipla', 'Múltipla Escolha'), ('vf', 'Verdadeiro ou Falso')], max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('ano_escolar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='LSDash.anoescolar')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to=settings.AUTH_USER_MODEL)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='LSDash.materia')),
            ],
        ),
        migrations.CreateModel(
            name='ImagemQuestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imagens_questoes/')),
                ('legenda', models.CharField(blank=True, max_length=255, null=True)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='LSDash.questao')),
            ],
        ),
    ]
