# Generated by Django 5.1.2 on 2025-04-23 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LSDash', '0005_grupoensino_materia_anoescolar_questao_imagemquestao'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternativaMultiplaEscolha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('correta', models.BooleanField(default=False)),
                ('ordem', models.IntegerField(default=0)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='LSDash.questao')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='FraseVerdadeiroFalso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('verdadeira', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frases_vf', to='LSDash.questao')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
    ]
