# Generated by Django 5.1.2 on 2025-04-23 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LSDash', '0006_alternativamultiplaescolha_fraseverdadeirofalso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='email_contato',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='responsavel',
        ),
        migrations.RemoveField(
            model_name='usuariomaster',
            name='nome',
        ),
    ]
