# Generated by Django 5.1.2 on 2025-04-23 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LSDash', '0007_remove_cliente_email_contato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_home_1', models.ImageField(blank=True, null=True, upload_to='imagens_sistema/home/')),
                ('imagem_home_2', models.ImageField(blank=True, null=True, upload_to='imagens_sistema/home/')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('tempo_maximo_inatividade', models.IntegerField(default=30, help_text='Tempo máximo de inatividade em minutos')),
            ],
        ),
        migrations.CreateModel(
            name='SessaoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_sessao', models.CharField(max_length=40)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('ultima_atividade', models.DateTimeField(auto_now=True)),
                ('endereco_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'chave_sessao')},
            },
        ),
    ]
