# Generated by Django 5.1.2 on 2025-04-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LSDash', '0008_configuracaosistema_sessaousuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='Enunciado'),
        ),
    ]
